### PR TITLE
fixed suggest-terms request method

### PR DESCRIPTION
**Pull request by reinhardt**
We need to make a GET request and use the 'word' key.

### CODE REVIEW

**Comment by tisto** [comment]
@reinhardt can you point me to the solr docs for this? Your changes break the build, please fix.

**Comment by reinhardt** [comment]
Solr docs: http://wiki.apache.org/solr/SpellCheckComponent#Extended_Results

or chapter "Spell Checking" in the reference guide.

Fix is pushed.

**Comment by reinhardt** [comment]
Hm, I think I made a wrong assumption here - the tests expect a dict to be returned, not only the "word" value. Will have another closer look.

**Comment by reinhardt** [comment]
There. Please forget about the 'word' key. Sorry about the noise.

**Comment by tisto** [comment]
@reinhardt I still can't find a reference to that change. Could you please add a change note with a link to a document that explains what "recent solr versions" mean exactly?

**Comment by reinhardt** [comment]
OK, apologies again, the "for recent solr versions" in the title may have been confusing now that I removed the part about the 'word' key.

About the request method: There was no change in solr. The request method should always have been GET. It just happened to work with POST in earlier solr versions.

It does not explicitly say you need to use GET in this section, but it's kinda implicit from the URL with the query string:

http://wiki.apache.org/solr/SpellCheckComponent#Example_Requests

Does this make it any clearer?

**Comment by tisto** [comment]
@reinhardt ok, GET makes more sense than POST since a search is an idempotent request which does not affect server state. Please update the changelog.

**Comment by reinhardt** [comment]
Changelog updated.

**Comment by tisto** [comment]
@reinhardt thx!

**Comment by reinhardt** [comment]
Thank _you_!

**Pull request merged**
