### PR TITLE
Plone 5 compatibility (kitconcept branch)

### PR DESCRIPTION
**Pull request by tisto**
This pull request includes:

- Plone 5 compatibility
- Plone 5 search UI based on React
- Settings stored in plone.app.registry

Roadmap:

- [x] Create 5.x branch from current master
- [ ] Merge this pr and make it the new master branch
- [ ] Release plone.restapi 1.0a1
- [ ] Make this pr use plone.restapi 1.0a1
- [ ] Fix remaining test isolation issues
- [ ] Make sure we do not skip any tests
- [ ] Make sure test coverage is > 90 % (as it was before the refactoring)
- [ ] Code cleanup
- [ ] Remove support for old Plone versions (< 4)
- [ ] Remove support for old Solr versions (< 4)
- [ ] Remove skins folder
- [ ] Remove browser views for Plone 4
- [ ] Remove search profile
- [ ] Release collective.solr 6.0 with Plone 5 support and a new react-based search UI

### CODE REVIEW

**Comment by tomgross** [comment]
Hi @tisto what is the state of this? Can I help to get Plone 5 support in master and released?

**Comment by gforcada** [comment]
I have this very same branch rebased on top of master, should I push it? It makes it quite more easier to follow what has happened...

**Comment by tisto** [comment]
@tomgross yes, of course! Please see the roadmap that I wrote, you can just grab any task. :)

@gforcada could you create a new pull request with your rebased local branch?

**Comment by gforcada** [comment]
@tisto done: https://github.com/collective/collective.solr/pull/127

**Comment by tisto** [comment]
@tomgross @gforcada I merged gil's pr and moved the roadmap to a new issue: https://github.com/collective/collective.solr/issues/128

**Pull request closed without merging**
