### PR TITLE
fix unicodeerror in binary adder and use public method to get blob path first

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by mitakas** [comment]
I get `BlobError: Uncommitted changes` in Plone 4.3.3 when trying to add content. Removing the [`blob.commited()`](https://github.com/collective/collective.solr/commit/d93399a82a33469f6560a9137a5cc7e78cac1601#diff-6c045cfe6307fd329498dfe3e0f948daR118) call solves it:

```
2015-03-13 12:29:04 ERROR Zope.SiteErrorLog 1426246144.990.308674131041 #/portal_factory/Image/image.2015-03-13.9963699771/atct_edit
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.FactoryTool, line 478, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 28, in _call
  Module Products.CMFFormController.ControllerBase, line 231, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 107, in __call__
  Module Products.CMFFormController.ControllerBase, line 231, in getNext
  Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPythonScript, line 105, in __call__
  Module Products.CMFFormController.Script, line 145, in __call__
  Module Products.CMFCore.FSPythonScript, line 127, in __call__
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 344, in _exec
  Module script, line 1, in content_edit
   - <FSControllerPythonScript at /#/content_edit used for /#/portal_factory/Image/image.2015-03-13.9963699771>
   - Line 1
  Module Products.CMFCore.FSPythonScript, line 127, in __call__
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 344, in _exec
  Module script, line 8, in content_edit_impl
   - <FSPythonScript at /#/content_edit_impl used for /#/portal_factory/Image/image.2015-03-13.9963699771>
   - Line 8
  Module Products.CMFPlone.FactoryTool, line 321, in doCreate
  Module Products.ATContentTypes.lib.constraintypes, line 284, in invokeFactory
  Module Products.CMFCore.TypesTool, line 833, in constructContent
  Module Products.CMFCore.TypesTool, line 311, in constructInstance
  Module Products.CMFCore.TypesTool, line 559, in _constructInstance
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module Products.CMFCore.CMFCatalogAware, line 262, in handleContentishEvent
  Module Products.CMFCore.CMFCatalogAware, line 188, in notifyWorkflowCreated
  Module Products.CMFCore.WorkflowTool, line 289, in notifyCreated
  Module Products.CMFCore.WorkflowTool, line 639, in _reindexWorkflowVariables
  Module Products.Archetypes.CatalogMultiplex, line 66, in reindexObjectSecurity
  Module collective.indexing.monkey, line 89, in unrestrictedSearchResults
  Module collective.indexing.queue, line 39, in processQueue
  Module collective.indexing.queue, line 165, in process
  Module collective.solr.indexer, line 217, in reindex
  Module collective.solr.indexer, line 212, in index
  Module collective.solr.indexer, line 138, in __call__
  Module collective.solr.indexer, line 117, in getpath
  Module ZODB.blob, line 202, in committed
BlobError: Uncommitted changes
```

**Comment by do3cc** [comment]
@tomgross, can you tell what `committed()`
actually fixed on maintenance/reindex?

**Comment by do3cc** [comment]
@saily

**Comment by tomgross** [comment]
Actually it needs to be the other way round:  
```python
>>> return blob._p_blob_committed or blob._p_blob_uncommitted or blob.committed()
```

**Comment by tomgross** [comment]
see comments in #6

**Comment by do3cc** [comment]
@mitakas, can you try this change to see if it solves your problem? I can then create a release with the fix.

**Comment by mitakas** [comment]
@do3cc Yes, this change -> https://github.com/collective/collective.solr/pull/42#issuecomment-80034991 fixes it.

**Pull request merged**
