### PR TITLE
Replace pypi.in badges with shield.io ones

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by tisto** [comment]
@gforcada I think it would be better if we move to shields.io instead of just removing those badges. See https://raw.githubusercontent.com/kitconcept/pas.plugins.memberpropertytogroup/master/README.rst for an example.

**Comment by gforcada** [comment]
@tisto thanks, I knew there was a new service (feels like JS frameworks this too :D) but I forgot its name.

I will update the pull request with shields.io links

**Comment by gforcada** [comment]
Now it should be fine

**Comment by tisto** [comment]
@gforcada thanks!

**Pull request merged**
