### PR TITLE
Plone 5.2 compat.

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
@reinhardt thanks for working on this!!! Let me know if there is anything I can do to help.

**Comment by reinhardt** [comment]
Cheers! For now I think I'm fine. But I expect I'll get back to you. :-)

**Comment by reinhardt** [comment]
Are there plans or thoughts about whether or not to support Plone < 5.1 (and therefore collective.indexing) in future versions? Right now c.indexing is commented out in setup.py; that would mean not supporting it in future versions of c.solr. If we put it back in we can support Plone < 5.1 and still mostly ignore it when using it in Plone >= 5.1... or can we? If it's included then the imports in the try/excepts will succeed, and the monkey patches may be activated etc. So I think we'd rather not have it in. Do we release a new major version that only supports Plone >= 5.1 then, and maintain a separate Plone < 5.1 version with backported bugfixes and all?

**Comment by tisto** [comment]
@reinhardt I think this is the more up-to-date branch for the Plone 5.2 compat: 

https://github.com/collective/collective.solr/pull/222

I'd try to keep both Plone 4.3/5.0 and 5.1/5.2 compatibility if possible. Though, if this turns out to be too much work, we have to create a 5.1 branch. TBH I got frustrated at some point when working on this. The c.indexing PLIP was merged without actually testing the only consumer (c.solr). We (as a community) put a lot of effort into it and ended up with a broken system in exchange and no real gain. 

Therefore I'd go with whatever we have to get the job done. I think the PR above is pretty close, it just needs some love. Solr 8 and Plone 5.1 just have one single test failure:

https://travis-ci.org/collective/collective.solr/jobs/530797155

@csenger can you tell what this last test failure is about?

**Comment by tisto** [comment]
Closing this in favor of https://github.com/collective/collective.solr/pull/222

**Pull request closed without merging**
