### PR TITLE
Fix Robot acceptance tests on Plone 4

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by sneridagh** [comment]
The acceptance tests for Plone 4 passes on master... so the amended tests already passes in master. @tisto @tomgross sorry but I can't tell the source of the problem... Am I missing something?

**Comment by tomgross** [comment]
@sneridagh Two acceptance tests are skipped on master. That's why they are passing 😉 
https://github.com/collective/collective.solr/blob/master/src/collective/solr/tests/robot/test_search.robot#L101

**Comment by tomgross** [comment]
These skips are removed in this branch

**Comment by sneridagh** [comment]
@tomgross got it! Thanks. I see what's happening, when the checkbox is clicked, the dropdown gets hidden :( I'll try to fix it.

**Comment by sneridagh** [comment]
@tisto @tomgross I've found the reason of the fail test. The "filter results" dropdown menu is conflicting with the default Plone 4 dropdown.js behavior and when you click on a checkbox, it hides the dropdown. This is the behaviour of all dropdowns in Plone 4. We cloned the markup in order to be the less intrusive possible that's because it's conflicting.

I would change the markup of the search.pt and put in place our own classes fully controlled by React, however this would take time.

**Comment by tisto** [comment]
@sneridagh what would be your estimate for the refactoring?

**Comment by sneridagh** [comment]
@tisto should take a couple of hours at most... the only drawback is that we will require to add a complimentary CSS, but we can pull it in with Webpack.

Question is, given the fact that it's only a reference implementation (as it is now) it's worth to keep 1:1 features with Plone 4?

**Comment by tisto** [comment]
@tomgross one of our clients needs a Solr integration in Plone 4. Therefore I will look into this. Are you folks also still on Plone 4 or did you upgrade in the meantime?

**Pull request closed without merging**
