### PR TITLE
Randomports

### PR DESCRIPTION
**Pull request by do3cc**
This PR would change the standard behavior of its Solr Layer to use a random port by default.
It requires a source checkout of collective.recipe.solrinstance.

### CODE REVIEW

**Comment by tisto** [comment]
@do3cc Could you elaborate what kind of problem the random port assignment solves for you? I'm not sure if the test fixture is the right level to solve this problem. Debugging becomes a bit harder when we assign a random port. I use the Solr analysis view a lot during tests and I would have to look up the port every single time. I guess I would prefer to keep a static port for this. You can always use the Jenkins port allocator plugin to assign a Solr port for CI. You can even dynamically load different Solr core configurations if needed (see https://github.com/tisto/solr-testing/blob/master/fixtures.py#L24).

**Comment by do3cc** [comment]
Hi,
I very often have problems with unclean shutdown of tests. Often because of running tests with -D, sometimes seemingly after errors in tests that end up keeping sold running.
I've helped myself by using in environment variable for setting the port dynamically.
Now I work in a project with many separate eggs and half a dozen of them requiring Solr. Now setting Solr ports independently does not work any more.

I am +1 for producing a helpful URL to access the admin interfaces and +1 for random port not being the default logic. So far I rarely needed to debug the Solr interface during tests, so I did not have this feature in my mind.

There is another PR in collective.recipe.solrinstance that will be helpful for this thing here. There was a bug in crs with setting the log file. With the PR it should be possible to tell Solr to be more silent.

**Comment by do3cc** [comment]
@tisto, I'd like to adapt the labels from the plone group and mark this PR WIP.
Right now I don't have this permission

**Comment by tisto** [comment]
@do3cc do you still plan to work on this? Otherwise I would close the pr...

**Comment by do3cc** [comment]
No. Random ports did not improve the situation. I now mount my solr as a docker container to the tests.

**Pull request closed without merging**
