### PR TITLE
Handle non-ascii values in the query.

### PR DESCRIPTION
**Pull request by reinhardt**
Fixes UnicodeDecodeError when searching for non-ascii text

### CODE REVIEW

**Comment by reinhardt** [comment]
Hey @tisto, would you have a moment to review this?
The build fails with version conflicts, is that a known issue?

**Comment by tisto** [comment]
@reinhardt looks like a problem with a zc.buildout version. We might want to switch to a virtualenv approach on travis to fix this.

**Comment by tisto** [comment]
@reinhardt pls merge master into your branch. This should fix the issue.

**Comment by reinhardt** [comment]
Thanks! I've rebased.

**Comment by reinhardt** [comment]
Yup, that did it!

**Comment by reinhardt** [comment]
Cheers!

**Pull request merged**
