### PR TITLE
feat: add support of https connections

### PR DESCRIPTION
**Pull request by remdub**
This PR adds support of https connections.

### CODE REVIEW

**Comment by mpeeters** [comment]
@remdub LGTM, add an entry in changelog

**Review by mpeeters — APPROVED** [review]

**Review by laulaz — APPROVED** [review]

**Review by davisagli — COMMENTED** [review]
The implementation looks good to me, but I would expect the new config options to be mentioned in the documentation. https://collectivesolr.readthedocs.io/en/latest/usage/config.html

**Comment by remdub** [comment]
> The implementation looks good to me, but I would expect the new config options to be mentioned in the documentation. https://collectivesolr.readthedocs.io/en/latest/usage/config.html

Done

**Review by davisagli — APPROVED** [review]
Thanks. @tisto any concerns about merging this?

**Comment by bsuttor** [comment]
I just rebase main to avoid conflicts, and LGTM

**Review by tisto — APPROVED** [review]
@remdub LGTM. Pls rebase. Then let's merge and release.

**Comment by remdub** [comment]
> @remdub LGTM. Pls rebase. Then let's merge and release.

Thank you. I've solved conflicts, ready to squash and merge !

**Pull request merged**
