### PR TITLE
Update default solrconfig.xml to include /suggest requestHandler

### PR DESCRIPTION
**Pull request by avoinea**
Update default solrconfig.xml to include /suggest requestHandler used by eea.facetednavigation autocomplete

See https://github.com/eea/eea.facetednavigation/blob/master/eea/facetednavigation/widgets/autocomplete/widget.py#L120

### CODE REVIEW

**Comment by tisto** [comment]
@avoinea I am undecided on this TBH. I added a suggest handler to c.solr long time ago and to be honest, I never used or updated it. Search requirements are usually pretty complex and it is hard to find a good base that's worth supporting.

I am not against merging this. Though, this is something I'd like to discuss a bit more in-depth maybe...

**Comment by avoinea** [comment]
@tisto The issue is that in `eea.facetednavigation` there is this SOLR autocomplete widget that expects `/suggest` SOLR endpoint for ages. Without docs on either side it just looks broken.

Oh, I see I already added docs on eea.facetednavigation side https://github.com/eea/eea.facetednavigation#suggestions :smile:

**Comment by tisto** [comment]
@avoinea do you still want this to be in? Sorry that I left this laying around for so long. Here is our latest suggest config:

https://github.com/kitconcept/pytest-solr/blob/master/tests/suggest/solrconfig.xml#L32

**Comment by avoinea** [comment]
@tisto As it's documented on eea.facetednavigation side, it's not a must. It's was just a nice to have :wink:

**Pull request closed without merging**
