### PR TITLE
Drop support for Python 2.6 and Plone 4.2

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by gforcada** [comment]
Isn't this getting a bit too big/broad? Reviewing so many changes can be a bit daunting :-/

**Comment by tomgross** [comment]
This is ready for merging @gforcada @tisto can you please review and merge?

**Comment by tomgross** [comment]
It fixes some of the items needed for a Plone 5 compatible release #128

**Comment by gforcada** [comment]
@tomgross looks fine, I rebased the branch on top of master and merged some commits together (the ones related to updating setup.py mostly).

As long as travis is happy I would say we can merge.

Thanks for the work!!

**Pull request merged**
