### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by reinhardt** [comment]
I only just realized that this PR does not point from the python3 branch to master, but from the python3 branch of a third repo to the python3 branch of this one. Maybe I should rebase my PR (#223) onto https://github.com/derFreitag/collective.solr/tree/python3 ... ?

**Comment by gforcada** [comment]
As you mention, this pulls commits from a `derFreitag` organization, and as you can see, the committers on that branch are not the same as the one that created this pull request... we (as I work at derFreitag) plan to get `collective.solr` to python 3 eventually, we are blocked right now by other projects that have higher priority.

If we work on our fork of collective.solr is mostly due to quite a few patches that are yet to be accepted and merged upstream. Our fork and port to python 3 will include those commits as well *eventually*, which does not make sense to put together within a pull request that its aim is to push for python 3 compatibility.

You are free to grab what's now there and create a new branch out of it, so you are free from those patches that we put on top of collective.solr.

**Comment by reinhardt** [comment]
As discussed in #210 I'll merge this and continue to work towards a stable state in the collective/python3 branch.

**Comment by reinhardt** [comment]
I can't merge here because of conflicts and/or travis fail. I'll take the liberty of pushing to the python3 branch directly.

**Comment by reinhardt** [comment]
I'm not so familiar with travis. I resolved the conflict by simply taking the version from derFreitag. @tisto, please let me know in case something useful has gotten lost.

**Pull request merged**
