### PR TITLE
Implement atomic updates with collective.receipe.solrinstance 6.0.0b3

### PR DESCRIPTION
**Pull request by maethu**
This is a followup of https://github.com/collective/collective.solr/pull/80.

Issue with #80:
- I'm unable to get a proper solrconfig.xml generated by c.r.solrinstance 5.x, which supports `<updateLog/>` for the atomic update feature.

So I went ahead using collective.receipe.solrinstance 6.0.0b3.

Issue with the current build:
To boost a document or index on add no longer works. 
I don't know really why, the request sent so solr contains the `<doc boost="100"...`. But solr seems to ignore it. Any suggestions how to solve this?

**UPDATE:**

Since the AtomicUpdates and index time boosting does not work together (at least in solr 4.10.x), I implemented a new config option for the solr control panel ``atomic_updates``.  It's enabled by default. 

Further I extended the docs with some important infos about the AtomicUpdate feature.

### CODE REVIEW

**Comment by maethu** [comment]
@tisto Tests are now fine :laughing: 

- Update the PR description
- Updated sphinx docu with AtomicUpdates
- Added new control panel option `atomic_updates`.
- Fixed tests according to the fact, that it's not possible to have index time boosting and atomic update enabled at the same time.

**Comment by maethu** [comment]
cc @lukasgraf @buchi

**Comment by tisto** [comment]
@maethu Awesome! Thanks! Will have a look later today...

**Comment by maethu** [comment]
Closed in favour of https://github.com/collective/collective.solr/pull/86

**Pull request closed without merging**
